package cn.guye.bitshares.operations;

import java.util.HashMap;
import java.util.Map;

/**
 * Enum type used to keep track of all the operation types and their corresponding ids.
 *
 * <a href="https://bitshares.org/doxygen/operations_8hpp_source.html">Source</a>
 *
 * Created by nelson on 11/6/16.
 */
public enum OperationType {
    TRANSFER_OPERATION(0),
    LIMIT_ORDER_CREATE_OPERATION(1),
    LIMIT_ORDER_CANCEL_OPERATION(2),
    CALL_ORDER_UPDATE_OPERATION(3),
    FILL_ORDER_OPERATION(4),
    ACCOUNT_CREATE_OPERATION(5),
    ACCOUNT_UPDATE_OPERATION(6),
    ACCOUNT_WHITELIST_OPERATION(7),
    ACCOUNT_UPGRADE_OPERATION(8),
    ACCOUNT_TRANSFER_OPERATION(9),
    ASSET_CREATE_OPERATION(10),
    ASSET_UPDATE_OPERATION(11),
    ASSET_UPDATE_BITASSET_OPERATION(12),
    ASSET_UPDATE_FEED_PRODUCERS_OPERATION(13),
    ASSET_ISSUE_OPERATION(14),
    ASSET_RESERVE_OPERATION(15),
    ASSET_FUND_FEE_POOL_OPERATION(16),
    ASSET_SETTLE_OPERATION(17),
    ASSET_GLOBAL_SETTLE_OPERATION(18),
    ASSET_PUBLISH_FEED_OPERATION(19),
    WITNESS_CREATE_OPERATION(20),
    WITNESS_UPDATE_OPERATION(21),
    PROPOSAL_CREATE_OPERATION(22),
    PROPOSAL_UPDATE_OPERATION(23),
    PROPOSAL_DELETE_OPERATION(24),
    WITHDRAW_PERMISSION_CREATE_OPERATION(25),
    WITHDRAW_PERMISSION_UPDATE_OPERATION(26),
    WITHDRAW_PERMISSION_CLAIM_OPERATION(27),
    WITHDRAW_PERMISSION_DELETE_OPERATION(28),
    COMMITTEE_MEMBER_CREATE_OPERATION(29),
    COMMITTEE_MEMBER_UPDATE_OPERATION(30),
    COMMITTEE_MEMBER_UPDATE_GLOBAL_PARAMETERS_OPERATION(31),
    VESTING_BALANCE_CREATE_OPERATION(32),
    VESTING_BALANCE_WITHDRAW_OPERATION(33),
    WORKER_CREATE_OPERATION(34),
    CUSTOM_OPERATION(35),
    ASSERT_OPERATION(36),
    BALANCE_CLAIM_OPERATION(37),
    OVERRIDE_TRANSFER_OPERATION(38),
    TRANSFER_TO_BLIND_OPERATION(39),
    BLIND_TRANSFER_OPERATION(40),
    TRANSFER_FROM_BLIND_OPERATION(41),
    ASSET_SETTLE_CANCEL_OPERATION(42),  // VIRTUAL
    ASSET_CLAIM_FEES_OPERATION(43);

    private final int type;

    private OperationType(int type){
        this.type = type;
    }
}
